### ISSUE TITLE
Quote printable email

### ISSUE THREAD

**Issue by victor-ponamarev** [captbaritone/codeception-mailcatcher-module#11]
Hi there.

I tried to use grabMatchesFromLastEmail method, and I was struggling with regexps. I really couldn't grab anything, event simple text (in cyrillic encoding). Then I realized that the email is encoded like quoted printable format.

So, it worked for me when I changed $email['source'] to quoted_printable_decode($email['source']) in grabMatchesFromEmail method.

Am I wrong and there is any other way to work with emails without thinking about all these "=3D=5B..." symbols?

**Comment by captbaritone** [comment]
@victor-ponamarev Since you've not responded, I'm going to close this issue. If you have an example, I can repopen
