### ISSUE TITLE
Why not to add codeception to require section of composer.json?

### ISSUE THREAD

**Issue by akireikin** [captbaritone/codeception-mailcatcher-module#14]

**Comment by captbaritone** [comment]
Good question. I think of requirements as packages that are subordinate to the packages that require them.

I don't think it would make sense for somebody to require `codeception-mailcatcher-module` without also requiring `codeception`.

I'd be happy to reconsider if you can show me the error in my thinking. Can you find another example of a package that is a module or plugin which requires that package that it is a module or plugin of?

I'll gladly reopen this issue if you would like to discuss it further.

**Comment by akireikin** [comment]
Thanks for your reply. I have got your point. And I partially agree with you.

If we add the line, nothing bad will happen. Moreover, those who forgot to add `require codeception` in `composer.json` became happy.

I made an investigation and found some packages as an example.
- [yii2-swiftmailer](https://github.com/yiisoft/yii2-swiftmailer) requires [yii2](https://github.com/yiisoft/yii2)
- [laravel-administrator](https://github.com/FrozenNode/Laravel-Administrator) requires [laravel](https://github.com/laravel/framework)
- [Behat Symfony2Extension](https://github.com/Behat/Symfony2Extension) requires [Symfony](https://github.com/symfony/symfony)
