### ISSUE TITLE
Error when running tests. Missing From argument.

### ISSUE THREAD

**Issue by opexus** [captbaritone/codeception-mailcatcher-module#15]
![2015-01-29 20-07-29 centos vagrant localhost var www opensource codeception-mailcatcher-module test ssh 132x38](https://cloud.githubusercontent.com/assets/2033719/5962126/8f57820c-a7f2-11e4-8ee5-c06788f55fc2.png)

The problem occurs when in PHP's `mail()` function `From` header is not settled. There are two possible workarounds:
1. Set `sendmail_from` in `php.ini`. By default it is `null`.
2. Always pass `From` header to `mail()` function.

Guess, the second option is much better. Tests should work correctly without changing default `php.ini` params.

**Comment by captbaritone** [comment]
Oh, saw this after merging your PR. Looks like we are on the same page :)

Thanks for the report, and the PR!

**Comment by opexus** [comment]
Thank you!
