### ISSUE TITLE
url attribute on messages?

### ISSUE THREAD

**Issue by agouticreative** [captbaritone/codeception-mailcatcher-module#22]
Hey, I've been using this module for a bit and really like it

I have a thought (and a commit) in regards to a user need that came up in other github issues, which is that of exploring/parsing the HTML of the email while testing.

in the issue threads, the headache of parsing html accurately is mentioned as a reason why there hasn't much movement on this.

Why not include the email's HTML preview URL on mailcatcher (for example, http://localhost:1080/messages/1.html) in the message data? Then the tester can simply use a line of code like `$tester->amOnPage($msg['url'])` to load the emails' HTML into the test browser. From there the full assortment of assertions and helper functions can be brought to bear on the email's content.

here's a commit that illustrates the idea:

https://github.com/agouticreative/codeception-mailcatcher-module/commit/075e0586e45a973b930922782d6fa75463eebc7f

What do you think? Apologies if this is in the code somewhere already and I stared through it, or if there is a fatal flaw to the idea...

**Comment by captbaritone** [comment]
Linking the related issue: https://github.com/captbaritone/codeception-mailcatcher-module/issues/10

Using Mailcatcher's HTML preview seems like a good idea. That being said, the `amOnPage` API seems a little awkward. Maybe we could gather up the assertions/actions that a user might want to take on the email's html and hide the encapsulate the `amOnPage` business inside our module? That way the user get's a more descriptive API like:

* `.seeInLastEmailHtml()`
* `.seeElementInLastEmailHtml()`

Just an idea. Are the number of actions that a user might want to take on some HTML too numerous for us to encapsulate within the module?

**Comment by margori** [comment]
I try to solve this with PR #35.
I need confirmation whether it is a good solution.
