### ISSUE TITLE
Update to guzzlehttp/guzzle

### ISSUE THREAD

**Issue by thinkspill** [captbaritone/codeception-mailcatcher-module#23]
Dependency `guzzle/guzzle` is now marked as abandoned: https://packagist.org/packages/guzzle/guzzle

**Comment by loren-osborn** [comment]
Looking at the release history, guzzle/guzzle 4.0.0 was 2+ months old when this package was pegged to guzzle/guzzle 3.x (which is rather reasonable under the circumstances)... The 4.0.0 release points at this document to assist with migration: https://github.com/guzzle/guzzle/blob/master/UPGRADING.md#3x-to-40

**Comment by captbaritone** [comment]
Anyone interested in opening a pull request?

**Comment by thinkspill** [comment]
Sure, I'll have one shortly.

**Comment by thinkspill** [comment]
I've opened the pull request. Let me know if you think it's mergeable or if something else is needed.

**Comment by captbaritone** [comment]
I've cut a new release: https://github.com/captbaritone/codeception-mailcatcher-module/releases/tag/1.2.1

**Comment by captbaritone** [comment]
Thanks!
