### ISSUE TITLE
Using guzzleRequestOptions did not work with new version

### ISSUE THREAD

**Issue by mstaatz** [captbaritone/codeception-mailcatcher-module#25]
Using guzzleRequestOptions did not work with new version. If you look at the magic method "__call" at guzzle client you can see that you have to call it with an uri and an option array.

`$this->mailcatcher->setDefaultOption($option, $value);` 

causes an execption.

Your tests never use optional parameters. Think this is why you didn't realized it.
Checked your acceptance.yml

best, Michael

**Comment by captbaritone** [comment]
Thanks for catching this. It looks to me like the best way to set default options would be via the array passed when creating the client:

> All other options passed to the constructor are used as default request options with every request created by the client.

-- http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client

**Comment by gdscei** [comment]
Hi, this problem has been resolved already, so I will close this issue. If it hasn't been for you yet, let me know.
