### ISSUE TITLE
problems with guzzle 5.3.1

### ISSUE THREAD

**Issue by oprudkyi** [captbaritone/codeception-mailcatcher-module#28]
it breaks in weird way 
[GuzzleHttp\Exception\RequestException] cURL error 3: <url> malformed
$I->resetEmails()
#9  vendor/captbaritone/mailcatcher-codeception-module/src/MailCatcher.php:50
#10 Codeception\Module\MailCatcher->resetEmails

while it's not big issue, but it took me sometime to understand 
as temporal fix user  can
- edit vendor/captbaritone/mailcatcher-codeception-module/src/MailCatcher.php
      $this->mailcatcher = new \GuzzleHttp\Client(['base_url' => $base_uri]);
  (i.e. change base_uri to base_url ) 
- or check what forces particular version of guzzle , in my case one of packages requires guzzle "<6"

**Comment by dzoeteman** [comment]
I think it would be best for this small project to not support Guzzle <6, as has been set by the composer.json, but I am open for debate.
