### ISSUE TITLE
Unified interface for testing email

### ISSUE THREAD

**Issue by JindrichPilar** [captbaritone/codeception-mailcatcher-module#33]
Hi,

I enjoy working with your module. It is very useful for functional/integration testing. However when it comes to acceptance testing it is not enough. For acceptance testing I need to access real email server. 

I think it would be useful to create an interface for testing email in the same way codeception uses interface ```Codeception\Lib\Interfaces\Web``` for WebDriver, PhpBrowser, Symfony modules and other. And implement this interface for MailCatcher and IMAP. 

Example usecase in continuous integration:
- Unit tests pass
- Functional tests pass
- build gets deployed to test server (with 99.99% production settings, including real SMTP)
- Acceptance tests run - try to register and confirm email
- delploy

There is already an imap module so it is not necessary to start from scratch  https://github.com/AhmedSamy/codeception-smtp-mail
(Which should be able to use IMAP, POP3 and NNTP)

**Comment by gdscei** [comment]
This is a great idea, but one problem is the difference between MailCatcher and regular SMTP - with MailCatcher you have an API available, with the module you've linked, you have to use a query language to get e-mails. How would you suggest to make this interface?

**Comment by Jamesking56** [comment]
This is quite old so I'm going to close. Feel free to reopen if you wanted to start a PR for this.
