### ISSUE TITLE
Add email screen when using screen recorder extension

### ISSUE THREAD

**Issue by EstebanSerfe** [captbaritone/codeception-mailcatcher-module#39]
Can we have the email contents been rendered (or the mailcatcher interface) be rendered with the selected email to display when using the screen recorder extension? https://codeception.com/extensions#Recorder

**Comment by Jamesking56** [comment]
Hi :wave: 

I've just taken over maintaining this package.

I've not used the recorder before so I'm not sure what is involved in providing this feature.

Does this require a GET request of some sort to view a page before taking a screenshot?

**Comment by Jamesking56** [comment]
Its been over a year since this, so I'm closing for now.
