### ISSUE TITLE
Readme instructions reference version 1.*

### ISSUE THREAD

**Issue by captbaritone** [captbaritone/codeception-mailcatcher-module#45]
I think you guys are on version 2 now.

<img width="914" alt="Screen Shot 2019-05-15 at 9 03 27 AM" src="https://user-images.githubusercontent.com/162735/57790862-734a7980-76f0-11e9-95a2-7f77dde4139d.png">

Thanks for all the work you've done on this project. I really appreciate that it has continued to provide value even after I've stopped writing PHP myself. ❤️

**Comment by dzoeteman** [comment]
Thanks - updated so we don't need to change it after every major, haha ;)

And thank you for your hard work on the initial versions!
