### ISSUE TITLE
2.1.0 release not on packagist

### ISSUE THREAD

**Issue by dzoeteman** [captbaritone/codeception-mailcatcher-module#46]
The 2.1.0 release did not seem to get updated on packagist - packagist still labels 2.0.0 as latest version available.

**Comment by dzoeteman** [comment]
@captbaritone Could you try a manual update on the packagist page? Thanks!

**Comment by captbaritone** [comment]
I logged into Packagist and it asked me for some GitHub permissions. I granted them and it seems to have automatically picked up 2.1.0.

@dzoeteman Do you have a packagist account? If so, let me know your username and I can add you as a maintainer. Thanks for all your work on this package. I really appreciate it!!

**Comment by dzoeteman** [comment]
@captbaritone Thanks! My username on packagist is 'gdscei'. It would be great if you could add me!
