### ISSUE TITLE
2.1.0 breaks backwards compatibility

### ISSUE THREAD

**Issue by Jamesking56** [captbaritone/codeception-mailcatcher-module#48]
https://github.com/captbaritone/codeception-mailcatcher-module/pull/44/files/6de65caf577478213d5b2556592c5678403ff7fc#diff-d8be5e6ff2f2b52ba87b1500f837d3a3

#44 breaks backwards-compatibility with codeception 2, some of the methods were changed to call codeception 3 methods which don't exist in codeception 2.

**Comment by magickreeator** [comment]
#49 must fix it

**Comment by Jamesking56** [comment]
@captbaritone are you in need of a new maintainer for this repo?

**Comment by dzoeteman** [comment]
@Jamesking56 I try to do some PRs here and there when I can, but I must admit I don't have a lot of time, nor am I actively using this project at the moment - so if someone wants to step in instead or help out, I think that would be a great idea depending on what @captbaritone thinks of it :)

**Comment by dzoeteman** [comment]
@magickreeator's PR is merged, and I've released 2.1.1 with this fix.
