### ISSUE TITLE
emailFromId converts = in Query String To ANSI characters

### ISSUE THREAD

**Issue by fbarrocal** [captbaritone/codeception-mailcatcher-module#50]
When I try to read an email that contains an URL with a query string the first couple characters after equal sign become decoded by quoted_printable_decode(), for example: 
Email boy like: 

> Check the list on page 56 at http://example.com/list.php?page=56

becomes: 

> Check the list on page 56 at http://example.com/list.php?pageV

Expected: 
URLs containing equal character followed by two hexadecimal characters does not translate into ANSI equivalent

**Comment by Jamesking56** [comment]
Hi :wave: 

I've just taken over maintaining this package.

Very strange bug! I will ear mark this for at least the next minor version (possibly before).
