### ISSUE TITLE
public function lastMessageFrom should be lastMessageTo

### ISSUE THREAD

**Issue by ghost** [captbaritone/codeception-mailcatcher-module#51]
The function looks for the address provided in the recipients of each message ... so I suspect the method name is a bit misleading ... perhaps.

**Comment by Jamesking56** [comment]
Yeah I agree, happy to PR if everyone agrees?

**Comment by hellodave76** [comment]
Especially as it's called from `seeInLastEmailTo`, would be clearer with this rename :+1:

**Comment by Jamesking56** [comment]
This should now be fixed
