### ISSUE TITLE
Non latin email subjects issue

### ISSUE THREAD

**Issue by lollypopgr** [captbaritone/codeception-mailcatcher-module#6]
Non latin subjects create a Header like this

```Subject: =?UTF-8?B?zpTOv866zrnOvM6uIM61zrvOu863zr3Ouc66z47OvSDPg8+Ezr/OvSA=?=
 =?UTF-8?B?z4TOr8+EzrvOvw==?=```

As a result, seeInLastEmail() is blind for non latin strings in the subject line.

**Comment by captbaritone** [comment]
@lollypopgr I'm closing this issue. If you want to give me a paste of the raw contents of this email, and the library you are using the generate the email, I can reopen the issue.
