### ISSUE TITLE
Support for HTTPS urls.

### ISSUE THREAD

**Issue by vuryss** [captbaritone/codeception-mailcatcher-module#78]
Hey dunno why but the regex here: 
https://github.com/captbaritone/codeception-mailcatcher-module/blob/b96143cce64f3e349e3d396f843687bb20c0b8ce/src/Module/MailCatcher.php#L287 is missing an 's'.

This is probably a typo, cause the 'p' is not usually optional.

This causes the https URLs to be ignored.

**Comment by Jamesking56** [comment]
Hey @vuryss

Thanks for sending in this issue.

It does appear that it is missing the `s` character. I've also noticed this is requiring all URLs to also end with a `/` character (which isn't always the case).

I will produce a fix for this and get a new patch release out.

**Comment by Jamesking56** [comment]
Released v2.3.1 to packagist - @vuryss please run `composer update captbaritone/mailcatcher-codeception-module` to get the patch :+1:

**Comment by vuryss** [comment]
Thanks for the quick update :) Cheers!
