### ISSUE TITLE
Upgrade `guzzlehttp/guzzle` to `^6.0|^7.0`?

### ISSUE THREAD

**Issue by ThomasLandauer** [captbaritone/codeception-mailcatcher-module#81]
Don't want to open another untested PR after https://github.com/captbaritone/codeception-mailcatcher-module/pull/80 ;-)

**Comment by Jamesking56** [comment]
Feel free to open one, I'll review them both and look to get them merged in. Thanks for improving the project 👍

**Comment by ThomasLandauer** [comment]
Sorry, just noticing that this is already done in v2.3...
